// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: internal/controlplane/protocol.proto

package controlplane

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RegisterRequest is the initial message from a plugin during registration
// (Step 1: REGISTER_REQUEST per SPEC 04 Section 4.2).
type RegisterRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PluginId             string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version              string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities         []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ManifestHash         string                 `protobuf:"bytes,5,opt,name=manifest_hash,json=manifestHash,proto3" json:"manifest_hash,omitempty"`
	EmergencyBypassTypes []string               `protobuf:"bytes,6,rep,name=emergency_bypass_types,json=emergencyBypassTypes,proto3" json:"emergency_bypass_types,omitempty"`
	Pid                  int32                  `protobuf:"varint,7,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RegisterRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetManifestHash() string {
	if x != nil {
		return x.ManifestHash
	}
	return ""
}

func (x *RegisterRequest) GetEmergencyBypassTypes() []string {
	if x != nil {
		return x.EmergencyBypassTypes
	}
	return nil
}

func (x *RegisterRequest) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// RegisterResponse is the core daemon's response to a plugin registration
// (Step 2: REGISTER_ACK per SPEC 04 Section 4.2).
type RegisterResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PluginId         string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	PluginIdRuntime  string                 `protobuf:"bytes,2,opt,name=plugin_id_runtime,json=pluginIdRuntime,proto3" json:"plugin_id_runtime,omitempty"`
	State            string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	EventBusUrl      string                 `protobuf:"bytes,4,opt,name=event_bus_url,json=eventBusUrl,proto3" json:"event_bus_url,omitempty"`
	EventBusToken    string                 `protobuf:"bytes,5,opt,name=event_bus_token,json=eventBusToken,proto3" json:"event_bus_token,omitempty"`
	ControlPlane     string                 `protobuf:"bytes,6,opt,name=control_plane,json=controlPlane,proto3" json:"control_plane,omitempty"`
	ConfigBundle     map[string]string      `protobuf:"bytes,7,rep,name=config_bundle,json=configBundle,proto3" json:"config_bundle,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PeerCapabilities []string               `protobuf:"bytes,8,rep,name=peer_capabilities,json=peerCapabilities,proto3" json:"peer_capabilities,omitempty"`
	Error            string                 `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RegisterResponse) GetPluginIdRuntime() string {
	if x != nil {
		return x.PluginIdRuntime
	}
	return ""
}

func (x *RegisterResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RegisterResponse) GetEventBusUrl() string {
	if x != nil {
		return x.EventBusUrl
	}
	return ""
}

func (x *RegisterResponse) GetEventBusToken() string {
	if x != nil {
		return x.EventBusToken
	}
	return ""
}

func (x *RegisterResponse) GetControlPlane() string {
	if x != nil {
		return x.ControlPlane
	}
	return ""
}

func (x *RegisterResponse) GetConfigBundle() map[string]string {
	if x != nil {
		return x.ConfigBundle
	}
	return nil
}

func (x *RegisterResponse) GetPeerCapabilities() []string {
	if x != nil {
		return x.PeerCapabilities
	}
	return nil
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HealthCheckRequest queries the health status of a specific plugin.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

// HealthCheckResponse contains the health status of a plugin per SPEC 18.
type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // HEALTHY|DEGRADED|ERROR|CRITICAL|UNRESPONSIVE
	State         string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`   // Current registry state string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// ListPluginsRequest is an empty request to list all registered plugins.
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsRequest.ProtoReflect.Descriptor instead.
func (*ListPluginsRequest) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{4}
}

// ListPluginsResponse contains all registered plugins.
type ListPluginsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInfo          `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPluginsResponse.ProtoReflect.Descriptor instead.
func (*ListPluginsResponse) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ListPluginsResponse) GetPlugins() []*PluginInfo {
	if x != nil {
		return x.Plugins
	}
	return nil
}

// PluginInfo contains summary information about a registered plugin.
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

// ShutdownPluginRequest initiates graceful shutdown of a plugin (SPEC 04 Section 4.3).
// Named ShutdownPluginRequest to avoid collision with the HandshakeManager's ShutdownRequest.
type ShutdownPluginRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PluginId           string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	GracePeriodSeconds int32                  `protobuf:"varint,2,opt,name=grace_period_seconds,json=gracePeriodSeconds,proto3" json:"grace_period_seconds,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ShutdownPluginRequest) Reset() {
	*x = ShutdownPluginRequest{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownPluginRequest) ProtoMessage() {}

func (x *ShutdownPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownPluginRequest.ProtoReflect.Descriptor instead.
func (*ShutdownPluginRequest) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *ShutdownPluginRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *ShutdownPluginRequest) GetGracePeriodSeconds() int32 {
	if x != nil {
		return x.GracePeriodSeconds
	}
	return 0
}

// ShutdownPluginResponse is the response to a shutdown request.
type ShutdownPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownPluginResponse) Reset() {
	*x = ShutdownPluginResponse{}
	mi := &file_internal_controlplane_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownPluginResponse) ProtoMessage() {}

func (x *ShutdownPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_controlplane_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownPluginResponse.ProtoReflect.Descriptor instead.
func (*ShutdownPluginResponse) Descriptor() ([]byte, []int) {
	return file_internal_controlplane_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *ShutdownPluginResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ShutdownPluginResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_internal_controlplane_protocol_proto protoreflect.FileDescriptor

const file_internal_controlplane_protocol_proto_rawDesc = "" +
	"\n" +
	"$internal/controlplane/protocol.proto\x12\fcontrolplane\"\xed\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x12#\n" +
	"\rmanifest_hash\x18\x05 \x01(\tR\fmanifestHash\x124\n" +
	"\x16emergency_bypass_types\x18\x06 \x03(\tR\x14emergencyBypassTypes\x12\x10\n" +
	"\x03pid\x18\a \x01(\x05R\x03pid\"\xbd\x03\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12*\n" +
	"\x11plugin_id_runtime\x18\x02 \x01(\tR\x0fpluginIdRuntime\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\"\n" +
	"\revent_bus_url\x18\x04 \x01(\tR\veventBusUrl\x12&\n" +
	"\x0fevent_bus_token\x18\x05 \x01(\tR\reventBusToken\x12#\n" +
	"\rcontrol_plane\x18\x06 \x01(\tR\fcontrolPlane\x12U\n" +
	"\rconfig_bundle\x18\a \x03(\v20.controlplane.RegisterResponse.ConfigBundleEntryR\fconfigBundle\x12+\n" +
	"\x11peer_capabilities\x18\b \x03(\tR\x10peerCapabilities\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x1a?\n" +
	"\x11ConfigBundleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\x12HealthCheckRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\"C\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\"\x14\n" +
	"\x12ListPluginsRequest\"I\n" +
	"\x13ListPluginsResponse\x122\n" +
	"\aplugins\x18\x01 \x03(\v2\x18.controlplane.PluginInfoR\aplugins\"`\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\"f\n" +
	"\x15ShutdownPluginRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x120\n" +
	"\x14grace_period_seconds\x18\x02 \x01(\x05R\x12gracePeriodSeconds\"L\n" +
	"\x16ShutdownPluginResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason2\xd8\x02\n" +
	"\fControlPlane\x12I\n" +
	"\bRegister\x12\x1d.controlplane.RegisterRequest\x1a\x1e.controlplane.RegisterResponse\x12R\n" +
	"\vHealthCheck\x12 .controlplane.HealthCheckRequest\x1a!.controlplane.HealthCheckResponse\x12R\n" +
	"\vListPlugins\x12 .controlplane.ListPluginsRequest\x1a!.controlplane.ListPluginsResponse\x12U\n" +
	"\bShutdown\x12#.controlplane.ShutdownPluginRequest\x1a$.controlplane.ShutdownPluginResponseB@Z>github.com/akashdas0307/kognis-core/core/internal/controlplaneb\x06proto3"

var (
	file_internal_controlplane_protocol_proto_rawDescOnce sync.Once
	file_internal_controlplane_protocol_proto_rawDescData []byte
)

func file_internal_controlplane_protocol_proto_rawDescGZIP() []byte {
	file_internal_controlplane_protocol_proto_rawDescOnce.Do(func() {
		file_internal_controlplane_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_controlplane_protocol_proto_rawDesc), len(file_internal_controlplane_protocol_proto_rawDesc)))
	})
	return file_internal_controlplane_protocol_proto_rawDescData
}

var file_internal_controlplane_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_controlplane_protocol_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: controlplane.RegisterRequest
	(*RegisterResponse)(nil),       // 1: controlplane.RegisterResponse
	(*HealthCheckRequest)(nil),     // 2: controlplane.HealthCheckRequest
	(*HealthCheckResponse)(nil),    // 3: controlplane.HealthCheckResponse
	(*ListPluginsRequest)(nil),     // 4: controlplane.ListPluginsRequest
	(*ListPluginsResponse)(nil),    // 5: controlplane.ListPluginsResponse
	(*PluginInfo)(nil),             // 6: controlplane.PluginInfo
	(*ShutdownPluginRequest)(nil),  // 7: controlplane.ShutdownPluginRequest
	(*ShutdownPluginResponse)(nil), // 8: controlplane.ShutdownPluginResponse
	nil,                            // 9: controlplane.RegisterResponse.ConfigBundleEntry
}
var file_internal_controlplane_protocol_proto_depIdxs = []int32{
	9, // 0: controlplane.RegisterResponse.config_bundle:type_name -> controlplane.RegisterResponse.ConfigBundleEntry
	6, // 1: controlplane.ListPluginsResponse.plugins:type_name -> controlplane.PluginInfo
	0, // 2: controlplane.ControlPlane.Register:input_type -> controlplane.RegisterRequest
	2, // 3: controlplane.ControlPlane.HealthCheck:input_type -> controlplane.HealthCheckRequest
	4, // 4: controlplane.ControlPlane.ListPlugins:input_type -> controlplane.ListPluginsRequest
	7, // 5: controlplane.ControlPlane.Shutdown:input_type -> controlplane.ShutdownPluginRequest
	1, // 6: controlplane.ControlPlane.Register:output_type -> controlplane.RegisterResponse
	3, // 7: controlplane.ControlPlane.HealthCheck:output_type -> controlplane.HealthCheckResponse
	5, // 8: controlplane.ControlPlane.ListPlugins:output_type -> controlplane.ListPluginsResponse
	8, // 9: controlplane.ControlPlane.Shutdown:output_type -> controlplane.ShutdownPluginResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_controlplane_protocol_proto_init() }
func file_internal_controlplane_protocol_proto_init() {
	if File_internal_controlplane_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_controlplane_protocol_proto_rawDesc), len(file_internal_controlplane_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_controlplane_protocol_proto_goTypes,
		DependencyIndexes: file_internal_controlplane_protocol_proto_depIdxs,
		MessageInfos:      file_internal_controlplane_protocol_proto_msgTypes,
	}.Build()
	File_internal_controlplane_protocol_proto = out.File
	file_internal_controlplane_protocol_proto_goTypes = nil
	file_internal_controlplane_protocol_proto_depIdxs = nil
}
